name: Release & Ship
on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current tag
        id: current_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Release new version
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.current_tag.outputs.tag }}
          body: "⚠️ Changelog not yet provided."
          files: ./release-${{ steps.current_tag.outputs.tag }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ship:
    needs: release
    # environment: build-ship
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            env/nginx/
            Dockerfile

      - name: Acquire Docker image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          # TODO: Add Docker Hub secrets then uncomment.
          # images: |
          #   proseim/prose-app-web
          #   ghcr.io/${{ github.repository }}
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}

      # TODO: Add Docker Hub secrets then uncomment.
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log into GitHub’s container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
          platforms: |
            linux/amd64
            linux/arm64
